name: AiRi
description: A Flutter AiRi.

version: 0.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_screenutil: ^5.0.0+2
  provider: ^5.0.0
  transparent_image: ^2.0.0
  flutter_swiper_null_safety: ^1.0.2
  cached_network_image: ^3.0.0
  webview_flutter: ^2.0.7
  permission_handler: ^8.0.0+2
  oktoast: ^3.0.0
  dio: ^4.0.0
  tuple: ^2.0.0
  pull_to_refresh: ^2.0.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.4
  sqflite: ^2.0.0+3
  convert: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # LOGO
    - assets/images/logo.png
    # 导航栏
    - assets/images/nav/nav_back.png
    # tab bar
    - assets/images/tabbar/zhuye_ON.png
    - assets/images/tabbar/zhuye_off.png
    - assets/images/tabbar/fenlei_ON.png
    - assets/images/tabbar/fenlei_off.png
    - assets/images/tabbar/diangdan_ON.png
    - assets/images/tabbar/dingdan_off.png
    - assets/images/tabbar/guanli_ON.png
    - assets/images/tabbar/guanli_off.png

    # 首页
    - assets/images/home/gouwuche.png
    - assets/images/home/sousuo.png
    - assets/images/home/gengduofenlei.png
    - assets/images/home/jiazaizhong.png
    - assets/images/home/fenxiang.png
    - assets/images/home/lianxi.png
    - assets/images/home/shop.png

    # 详情页
    - assets/images/detail/up.png
    - assets/images/detail/dowm.png

    # 供应商页面
    - assets/images/supplier/fenxiang.png
    - assets/images/supplier/beijing.png
    - assets/images/supplier/weizi.png
    - assets/images/supplier/lianxiren.png
    - assets/images/supplier/shijian.png

    # 购物车
    - assets/images/shopping_cart/bottom_check.png
    - assets/images/shopping_cart/check_un.png
    - assets/images/shopping_cart/check.png
    - assets/images/shopping_cart/down.png
    - assets/images/shopping_cart/down1.png
    - assets/images/shopping_cart/icon-sj-26.png
    - assets/images/shopping_cart/up.png
    - assets/images/shopping_cart/jiazaizhong.png
    - assets/images/shopping_cart/empty.png

    # 订单
    - assets/images/order/empty.png
    - assets/images/order/jiazaizhong.png
    - assets/images/order/querendingdan.png

    # 支付页
    - assets/images/pay/check.png
    - assets/images/pay/uncheck.png

    # 确认订单页面
    - assets/images/confirm_order/edit.png
    - assets/images/confirm_order/dingdanchenggong.png

    # 登录页面
    - assets/images/login/phone.png
    - assets/images/login/password.png

    # 字体图标
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
